ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.vm.define "etsi" do |h|
    h.vm.box = "bento/ubuntu-22.04"
    h.vm.hostname = 'etsi'

    # to create a private network with the name intnet-1, auto-config false because we will set the IPs and the network by ourself
    h.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    h.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false

    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "etsi"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end

    h.vm.provision "shell", path: "provision-tlmsp.sh"
    h.vm.provision "shell", path: "ip-etsi.sh", run: "always", name: "Set IPs"

    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "client" do |h|
    h.vm.box = "bento/ubuntu-22.04"
    h.vm.hostname = 'client'

    h.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false

    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "client"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end

    h.vm.provision "shell", path: "provision-client.sh"
    h.vm.provision "shell", path: "ip-client.sh", run: "always", name: "Set IPs"

    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "openfaas" do |h|
    h.vm.box = "bento/ubuntu-22.04"
    h.vm.hostname = 'openfaas'
    h.vm.network "forwarded_port", guest: 8080, host: 5001

    h.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false

    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "openfaas"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end

    h.vm.provision "shell", path: "provision-openfaas-root.sh", name: "Setup - root"
    h.vm.provision "shell", path: "provision-openfaas-user.sh", privileged: false, name: "Setup - user"
    h.vm.provision "shell", path: "ip-openfaas.sh", run: "always", name: "Set IPs"
    #h.vm.provision "shell", path: "startup-openfaas.sh", run: "always", name: "Start openfaas" #Port forwarding dies for some reason, run it manually after startup

    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "free5gc", autostart: false do |h|
    h.vm.box = "bento/ubuntu-22.04"
    h.vm.hostname = 'free5gc'
    h.vm.network "forwarded_port", guest: 5000, host: 5000

    h.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false

    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "free5gc"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end

    h.vm.provision "shell", path: "provision-free5gc-part1.sh"
    h.vm.provision "shell", reboot: true
    h.vm.provision "shell", path: "provision-free5gc-part2.sh"
    h.vm.provision "shell", path: "ip-free5gc.sh", run: "always", name: "Set IPs"

    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "etsi-20.04", autostart: false do |h|
    h.vm.box = "bento/ubuntu-20.04"
    h.vm.hostname = 'etsi-20.04'
    #h.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    #h.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false
    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "etsi-20.04"]
      v.cpus = 8
      #v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      #v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
    #h.vm.provision "shell", path: "ip-etsi.sh", run: "always"
    h.vm.provision "shell", path: "provision-tlmsp-20.04.sh", run: "always"
    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "client-20.04", autostart: false do |h|
    h.vm.box = "bento/ubuntu-20.04"
    h.vm.hostname = 'client-20.04'
    h.vm.network "private_network", virtualbox__intnet: "intnet-1", auto_config: false
    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "client-20.04"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end
    h.vm.provision "shell", path: "ip-free5gc.sh", run: "always"
    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end

  config.vm.define "server-20.04", autostart: false do |h|
    h.vm.box = "bento/ubuntu-22.04"
    h.vm.hostname = 'server-20.04'
    h.vm.network "private_network", virtualbox__intnet: "intnet-2", auto_config: false
    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "server-20.04"]
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end
    h.vm.provision "shell", path: "ip-openfaas.sh", run: "always"
    h.vm.synced_folder "..", "/home/vagrant/shared"
    h.vm.synced_folder "../..", "/home/vagrant/external"
  end
end
